INSERT INTO task(name) VALUE ('5 + 3');
INSERT INTO task(name) VALUE ('5 - 3');
INSERT INTO task(name) VALUE ('6 / 2');
INSERT INTO task(name) VALUE ('8 * 4');
INSERT INTO task(name) VALUE ('12 + 8');
INSERT INTO task(name) VALUE ('45 + 3');
INSERT INTO task(name) VALUE ('55 - 32');
INSERT INTO task(name) VALUE ('68 / 2');
INSERT INTO task(name) VALUE ('84 * 1');
INSERT INTO task(name) VALUE ('12 + 9');
INSERT INTO task(name) VALUE ('52 + 3');
INSERT INTO task(name) VALUE ('51 - 3');
INSERT INTO task(name) VALUE ('66 / 6');
INSERT INTO task(name) VALUE ('8 * 9');
INSERT INTO task(name) VALUE ('77 + 8');
INSERT INTO country(name) VALUE ('Ukraine');
INSERT INTO country(name) VALUE ('Poland');
INSERT INTO country(name) VALUE ('Germany');
INSERT INTO city(name,population,capital,country_id) VALUES ('Lviv',724314,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Kyiv',2967360,true,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Kharkiv',1443207,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Dnipro',990724,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Mykolaiv',480080,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Odesa',1017699,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Vinnytsya',370607,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Ternopil',223462,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Lutsk',217315,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Zaporizhya',731922,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Rivne',246000,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Sarny',29066,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Mukachevo',85796,false,1);
INSERT INTO city(name,population,capital,country_id) VALUES ('Hust',28321,false,1);

INSERT INTO city(name,population,capital,country_id) VALUES ('Warszawa',1706624,true,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Krakow',756583,false,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Lodz',753192,false,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Wroclaw',632930,false,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Poznan',560932,false,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Gdansk',455517,false,2);
INSERT INTO city(name,population,capital,country_id) VALUES ('Lublin',351806,false,2);

INSERT INTO city(name,population,capital,country_id) VALUES ('Berlin',3644826,true,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Gamburg',1841179,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Munhen',1471508,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Keln',1085664,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Shtutgart',634830,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Dusseldorf',619294,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Leypcig',587857,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Bremen',569352,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Hannover',538068,false,3);
INSERT INTO city(name,population,capital,country_id) VALUES ('Drezden',554649,false,3);